### ISSUE TITLE
Can filtering be disabled?

### ISSUE THREAD

**Issue by adamish** [lexemmens/podman-maven-plugin#27]
I've been debugging an issue whereby a Containerfile containing instructions like this

```
ENV OSPL_HOME=/opt/x/y/z
ENV CLASSPATH="${OSPL_HOME}/jar/*:${CLASSPATH}"
```
ends up being being processed as
```
ENV OSPL_HOME=/foo
ENV CLASSPATH="/bar//jar/*:${CLASSPATH}"
```
where /bar is the value from the maven script running podman. 

This appears to be due to filtering of the Containerfile. 
```
"[INFO] Filtering Containerfile..."
```

Can this be disabled? or can I escape the ${OSPL_HOME} in some way?

**Comment by lexemmens** [comment]
Hi Adam,

Thanks for your question. You're suspicion is indeed true. The reference to `${OSPL_HOME}` is actually treated as a possible Maven property and therefore matched against the properties of your Maven-project. 

From you're explanation I understand that you're Maven project also contains a property called `OSPL_HOME`. Therefore `${OSPL_HOME}` in the Containerfile is replaced and you will get the result as described.

Now, unfortunately, disabling filtering is not possible, but there is another way that has the desired effect. Just like in a Shell, there are two ways of referring to environment variables. You can either refer to a variable as `${VARIABLE}`, or you can leave out the curly braces and refer to the variable as `$VARIABLE`. Both notations are also supported by [Docker and Podman](https://docs.docker.com/engine/reference/builder/).

I took the liberty of testing this by changing `${OSPL_HOME}` to `$OSPL_HOME`:

*Before*
```Dockerfile
# Unfiltered Containerfile
ENV OSPL_HOME=/opt/x/y/z
ENV CLASSPATH="$OSPL_HOME/*:${CLASSPATH}"
```

*After*
```Dockerfile
# Filtered Containerfile
ENV OSPL_HOME=/opt/x/y/z
ENV CLASSPATH="$OSPL_HOME/jar/*:${CLASSPATH}"
```

When running the container it now prints:
`CLASSPATH= /opt/x/y/z/jar/*:bar/jar/*:`

Hope this helps!

**Comment by adamish** [comment]
Thanks for your quick reply and suggested workaround. 
Yes OSPL_HOME exists on the Jenkins build slave, it points to a "HDE" path, but our production uses "RTS" target (subtly different path, ones a runtime and ones a development kit)

**Comment by lexemmens** [comment]
Glad I could help!
