### ISSUE TITLE
Tagging stage might skip last step

### ISSUE THREAD

**Issue by abroekhuis** [lexemmens/podman-maven-plugin#32]
If a step of a stage produces multi-line output, the hash of that specific step is not recorded. As a result, if this happens at the last step of a stage, the wrong step (layer) might be tagged. Resulting in incomplete images.

**Comment by lexemmens** [comment]
I think I have implemented a potential solution as we discussed earlier. I do need to check the conditions on the warning I added in the `BuildOutputUtil`, in order to see if that's correct, before merging the attached PR.
