### ISSUE TITLE
Request: support for processing Containerfiles in batches

### ISSUE THREAD

**Issue by abroekhuis** [lexemmens/podman-maven-plugin#35]
I have a situation in which multiple containerfiles are generated, instead of having to specify each file explicitly, I'd like to be able to process all Containerfiles recursively found in a directory.

The following example is based on the existing <image> configuration:

```XML
<imageBatch> // new configuration item
                 <name>my/podman/image/${directory}</name> // This needs some variable solution in which eg the directory name containing the Containerfile is used 
                
                <customImageNameForMultiStageContainerfile>true</customImageNameForMultiStageContainerfile>
                <stages> // This assumes that similar stages are used in the Containerfiles
                    <stage>
                        <name>test</name>
                        <imageName>my-alternative-${directory}-image-name</imageName> // This needs some variable solution in which eg the directory name containing the Containerfile is used 
                    </stage>
                </stages>

                <build>
                    <noCache>true</noCache>
                    <containerFile>Containerfile</containerFile>
                    <containerFileDir>path/to/a/directory</containerFileDir> // instead of a path to the actual Containerfile, this is the path to the directory which has to be traversed to find Containerfiles
                    <pull>true</pull>
                    <pullAlways>true</pullAlways>

                    <tagWithMavenProjectVersion>false</tagWithMavenProjectVersion>
                    <createLatestTag>false</createLatestTag>

                    <tags>
                        <tag>1.0.0-SNAPSHOT</tag>
                        <tag>0.3.0-beta</tag>
                    </tags>

                    <labels>
                        <label-one>value-one</label-one>
                    </labels>

                    <format>OCI</format>
                </build>
            </imageBatch>
```

Afaict, only the following elements need specific handling:
* name: needs some way to make each image unique (eg based on the directory)
* stages/stage/imagename: same as name
* build/containerFileDir: instead of the actual directory with the containerfile, starting point for the recursive search

Given this directory structure:
/path/to/containerfiles/
- /mycontainerA/Containerfile
- /mycontainerB/Containerfile
- /othercontainers/containerX/Containerfile
- /**/Containerfile

The following (minimal) configuration could be used:
```
<imageBatch>
  <name>my/project/${directory}</name>
  <stages>
    <stage>
      <name>test</name>
      <imageName>my/project/${directory}/test</imageName>
    <stage>
  <stages>

  <build>
    <containerFileDir>/path/to/containerFiles</containerFileDir>
    ...
  </build>
  </imageBatch>
```

This will result in the following images:
* my/project/mycontainerA:${tags}
* my/project/mycontainerB:${tags}
* my/project/containerX:${tags}

Known shortcomings that I can see is:
* name clashes due to similar subdirectories in different branches of the directory
* No similar stages in Containfiles, but I don't think this is an issue, only specified (and declared in the configuration) stages can be processed.
But there are probably some more things that need some more thought.

**Comment by lexemmens** [comment]
We discussed this offline and we agree that this would be a nice enhancement. 

With respect to the name of the image we might opt to look at a formatter. This formatter then looks for formatting parameters and if none present appends the directory name at the end of the image name.

As for the `containerFileDir`: This is the root from where Containerfiles will be searched.

On the subject of configuration the proposal is to make the `ImageConfiguration` class an abstract class and introduce a new `SingleImageConfiguration` class for the existing configuration and a new `BatchImageConfiguration` for the newly requested batch feature. This way we can reuse the code as much as possible.

For pushing a batch of images it is absolutely necessary to search the directory for all the Containerfiles, because we need the directory names if no formatting parameters are specified.

**Comment by lexemmens** [comment]
I have opened a PR (which is linked to this issue) that contains the requested implementation. Unit tests still need to be added but based on CLI testing I think its good enough for an alpha release.

**Comment by lexemmens** [comment]
For testing purposes, a `1.6.0-alpha1` release is now available, including the requested enhancement, as well as #32 and #36. Documenation is available on [here](https://lexemmens.github.io/podman-maven-plugin/docs/1.6.0-alpha1/index.html)
