### ISSUE TITLE
Build failed with podman 3.1.0

### ISSUE THREAD

**Issue by palos-ba** [lexemmens/podman-maven-plugin#42]
It seems podman in 3.1.0 broke this plugin - with message "can only set one of 'pull' or 'pull-always' or 'pull-never'"

Tracked to this commit: https://github.com/containers/podman/pull/9631/commits/4d5199537737b0cfef47d3d2700013a787126d21

**Comment by lexemmens** [comment]
Interesting, thanks for bringing this under my attention. Seems like a pretty straightforward fix. I will take a look at it.
