### ISSUE TITLE
looking for complete example pom.xml files using podman-maven-plugin

### ISSUE THREAD

**Issue by erikerlandson** [lexemmens/podman-maven-plugin#54]
Some complete pom.xml files using `podman-maven-plugin` would be helpful for those of us who are not maven experts

**Comment by erikerlandson** [comment]
I got it working, so here's an example:
https://github.com/os-climate/trino-github-group-provider/blob/main/plugin/pom.xml#L78

**Comment by lexemmens** [comment]
Hi @erikerlandson, thanks for reaching out! Glad you managed to get it working. Nevertheless I will update the documentation with a working example.
