### ISSUE TITLE
Help Needed/Feature Request: build arguments for build

### ISSUE THREAD

**Issue by chrbrnracn** [lexemmens/podman-maven-plugin#59]
Hi Lex,

I'm migrating from fabric8 docker-maven-plugin to podman-maven-plugin. In the build I need to hand over build arguments to the Image build process (formerly Docker, now Podman).

The relevant section of for the docker-maven-plugin looks like this. with <args><argName>argValue</argName></args> you can hand over build arguments for the Docker build.
```xml
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<configuration>
		<skip>${docker.skip}</skip>
		<images>
			<image>
				<name>${registry.url}/${project.artifactId}:${env.image_tag}</name>
				<build>
					<contextDir>${project.basedir}</contextDir>
					<dockerFile>${docker.image.basedir}/Dockerfile</dockerFile>
					<args>
						<JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
					</args>
				</build>
			</image>
		</images>
	</configuration>
</plugin>
```

I couldn't find anything in the documentation and at least PodmanExecutorService.java doesn't have the relevant Podman option ([--build-arg=arg=value](https://docs.podman.io/en/latest/markdown/podman-build.1.html#build-arg-arg-value)

Did I miss the option? Then I would be happy if you could point me to the right direction. Otherwise I'd like to treat this as Feature Request.

Thanks,
Christian

**Comment by lexemmens** [comment]
Hi Christian, 

Thanks for reaching out! You didn't miss the option, it is not (yet) available. Therefore I will be treating this as a feature request. I have some other issues and features on the to-do list of the plugin I need to work on, so I am planning to include it in the next release.

Best regards,
Lex

**Comment by thucke** [comment]
+1
Need a possibility to set at least VERSION and REVISION using plugin configuration to use it in our CI/CD pipelines.

**Comment by AliaksandrShamchonak** [comment]
+1

**Comment by lexemmens** [comment]
I know this has been way too long, but I have been way too busy with other stuff. I opened a PR with the implementation as proposed above.
