### ISSUE TITLE
Plugin does not work on Windows

### ISSUE THREAD

**Issue by cerker** [lexemmens/podman-maven-plugin#82]
I have Podman running on Windows and thought I could use the Plugin to build my Images. However, it always fails because a "sestatus" command is executed which of course is not available on Windows and supposedly on Mac neither. After a quick look at the code there doesn't currently seem to be a way to work around this check. 

Would it be possible to skip this in future versions when running on other OSs than Linux or is this crucial to the way this plugin works?

I'm running the current version 1.15.1 on Windows 10 with Podman 4.5.0 on WSL2.

**Comment by lgranie** [comment]
Hi,
Same here.

**Comment by lexemmens** [comment]
I have been extremely busy in the past couple of weeks. Therefore I have been unable to look into this issue and PR earlier. I have seen the PR and added a small comment. If that is resolved I can make a new release which should again work on Windoes :-)
