### ISSUE TITLE
Documentation is not in line with implementation

### ISSUE THREAD

**Issue by kumadee** [lexemmens/podman-maven-plugin#87]
1. `podman.image.push.registry` as mentioned below doesn't work. The correct parameter is `podman.push.registry`. 
https://github.com/lexemmens/podman-maven-plugin/blob/9de0c881b794276aeaa75aa6c726a2f6e6560e07/docs/modules/ROOT/pages/general-configuration.adoc?plain=1#L35
https://github.com/lexemmens/podman-maven-plugin/blob/9de0c881b794276aeaa75aa6c726a2f6e6560e07/src/main/java/nl/lexemmens/podman/AbstractPodmanMojo.java#L53

1. The minimum maven version requirement is not up to date. It is should be either `3.8.5 or later` or the `maven.version` should be lowered in the pom.xml
https://github.com/lexemmens/podman-maven-plugin/blob/9de0c881b794276aeaa75aa6c726a2f6e6560e07/docs/modules/ROOT/pages/index.adoc?plain=1#L44
https://github.com/lexemmens/podman-maven-plugin/blob/9de0c881b794276aeaa75aa6c726a2f6e6560e07/pom.xml#L41

      ```bash
      # Below error was thrown when build was done with maven version == 3.6.3
      [ERROR] Failed to execute goal nl.lexemmens:podman-maven-plugin:1.17.0:build (podman-build) on project containers: The plugin nl.lexemmens:podman-maven-plugin:1.17.0 requires Maven version 3.8.5 -> [Help 1]
      ```

**Comment by lexemmens** [comment]
Hi @kumadee,

Thank you very much for all your contributions! It is really appreciated. I have approved and merged all pull requests you offered and will make a new release of the plugin :+1:
